version: '2'

services:
    nginx: 
        container_name: nginx
        restart: unless-stopped
        image: nginx:1.18.0
        ports:
            - 80:80
        volumes:
            - static_volume:/app/moisture_app/django_static
            - ./nginx:/etc/nginx/conf.d
        depends_on: 
            - django
    django:
        container_name: django
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app:delegated
            - static_volume:/app/moisture_app/django_static
        expose:
            - 8000    
        stdin_open: true
        depends_on:
            - postgres
        tty: true
    postgres:
        container_name: postgres
        image: postgres:11.5-alpine
        environment:
        - POSTGRES_PASSWORD=moisture
        - POSTGRES_USER=postgres
        - POSTGRES_DB=moisture
        volumes:
        - pg_data:/var/lib/postgresql/data
        ports:
        - "5433:5432"

volumes:
    static_volume: {}
    pg_data: 